development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: coffee_dev
  pool: 5
  username: root
  password: orangutan
  socket: /tmp/mysql.sock
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: coffee_test
  pool: 5
  username: root
  password: orangutan
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: coffee_prod
  pool: 5
  username: root
  password: orangutan
  socket: /tmp/mysql.sock
